name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LaTeX
        run: sudo apt-get install texlive texlive-xetex
      - name: Compile PDF
        run: |
          make
